// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgophpgjfcpkeexntxro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnb3BocGdqZmNwa2VleG50eHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTU5OTUsImV4cCI6MjA2MDk5MTk5NX0.yn23XxBmgPBRRtrfZ0DPVqYESFd6Zm28r5B8EVB3xA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);